apiVersion: cloudnative.redhat.com/v1alpha1
kind: ServiceConfig
metadata:
  name: example-serviceconfig
spec:
  enabled: true
  gitUrl: "https://github.com/cvicens/archetype-operator-customer-service.git"
  gitRef: "master"
  descriptorsFolder: "k8s"
  serviceName: "fruit-inventory"
  minReplicas: 2
  image: "fruits-1/fruit-inventory:dev"
  labels:
    app: fruit-inventory
    group: com.yourcompany.newapp
    provider: fabric8
    version: 1.0.0
  env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: user
          name: my-database-secret
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: my-database-secret
    - name: JAVA_OPTIONS
      value: '-Dspring.profiles.active=openshift'
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 180
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 180
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  volumeMounts:
    - mountPath: /external-data
      size: 10G
