// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfig":       schema_pkg_apis_cloudnative_v1alpha1_ServiceConfig(ref),
		"github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfigSpec":   schema_pkg_apis_cloudnative_v1alpha1_ServiceConfigSpec(ref),
		"github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfigStatus": schema_pkg_apis_cloudnative_v1alpha1_ServiceConfigStatus(ref),
	}
}

func schema_pkg_apis_cloudnative_v1alpha1_ServiceConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ServiceConfig is the Schema for the serviceconfigs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfigSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfigStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfigSpec", "github.com/redhat/service-config-operator/pkg/apis/cloudnative/v1alpha1.ServiceConfigStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cloudnative_v1alpha1_ServiceConfigSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ServiceConfigSpec defines the desired state of ServiceConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cloudnative_v1alpha1_ServiceConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ServiceConfigStatus defines the observed state of ServiceConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
