apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion":"cloudnative.redhat.com/v1alpha1","kind":"ServiceConfig","metadata":{"name":"example-serviceconfig"},
          "spec":
            {
              "descriptorsFolder":"k8s","enabled":true,
              "env":
                [
                  {"name":"DB_USERNAME","valueFrom":{"secretKeyRef":{"key":"user","name":"my-database-secret"}}},
                  {"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"my-database-secret"}}},
                  {"name":"JAVA_OPTIONS","value":"-Dspring.profiles.active=openshift"}
                ],
              "gitRef":"master",
              "gitUrl":"https://github.com/cvicens/archetype-operator-customer-service.git",
              "image":"fruits-1/fruit-inventory:dev",
              "labels":{"app":"fruit-inventory","group":"com.yourcompany.newapp","provider":"fabric8","version":"1.0.0"},
              "livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":180,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"minReplicas":2,
              "readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":180,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},
              "serviceName":"fruit-inventory","volumeMounts":[{"mountPath":"/external-data","size":"10G"}]
              }
          }
        ]
    capabilities: Basic Install
  name: service-config-operator.v0.0.1
  namespace: REPLACE_NAMESPACE
spec:
  displayName: Service Config Operator
  description: Blah blah blah
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
  labels:
    name: service-config-operator
  selector:
    matchLabels:
      name: service-config-operator
  links:
    - name: Service Config Operator Source Code
      url: https://github.com/cvicens/service-config-operator
  icon:
    - base64data: >- 
        PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE3LjEuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPg0KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgdmlld0JveD0iMCAwIDIxMy41NjMgMjEzLjU2MyIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMjEzLjU2MyAyMTMuNTYzOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQo8cGF0aCBkPSJNMTU4LjMzOSw2OC4zMzJsLTM4LjAxMiwzOC4wMTNjLTEuNjU0LTMuMjIyLTMuODIyLTYuMjQ3LTYuNTE4LTguOTQyYy0yLjY2NC0yLjY2NC01LjY3OC00Ljg0OC04LjkzMy02LjUyNmwzOC4wMTEtMzguMDExDQoJYzIuODYsMi4yMzIsNS42MTUsNC42MzIsOC4yMjEsNy4yMzhDMTUzLjcwMSw2Mi42OTYsMTU2LjEwMyw2NS40NTQsMTU4LjMzOSw2OC4zMzJ6IE03My44MTYsMTM3LjM5NQ0KCWMzLjkyNSwzLjkyNSw5LjE0Myw2LjA4NiwxNC42OTMsNi4wODZjNS41NSwwLDEwLjc2OC0yLjE2MiwxNC42OTItNi4wODZjOC4xMDItOC4xMDIsOC4xMDItMjEuMjg0LDAtMjkuMzg2DQoJYy0zLjkyNC0zLjkyNC05LjE0My02LjA4Ni0xNC42OTItNi4wODZjLTUuNTUxLDAtMTAuNzcsMi4xNjItMTQuNjk0LDYuMDg2QzY1LjcxNSwxMTYuMTExLDY1LjcxNSwxMjkuMjk0LDczLjgxNiwxMzcuMzk1eg0KCSBNMjEwLjExNiwxMTQuNTYxYy0wLjAwOC0wLjAwNy0wLjA3Ny0wLjA3Ny0wLjA4NC0wLjA4NGMtMi4yMzYtMi4yMzYtNS4yMS0zLjQ2Ny04LjM3Mi0zLjQ2N2MtMy4xNjMsMC02LjEzNywxLjIzMi04LjM3MiwzLjQ2OA0KCWwtOS41MDMsOS41MDNsLTAuMTMyLTAuMDA1bDI0LjYwOC01Ny40MzRjMS4yMDgtMi44MTgsMC41NzgtNi4wODgtMS41OS04LjI1N2wtOC41MzYtOC41MzZsLTczLjg4Niw3My44ODcNCgljLTAuMjI5LDguODQ4LTMuNzAyLDE3LjYyOC0xMC40NCwyNC4zNjZjLTYuNzU5LDYuNzU4LTE1Ljc0MywxMC40OC0yNS4zLDEwLjQ4Yy05LjU1OCwwLTE4LjU0Mi0zLjcyMi0yNS4zMDEtMTAuNDgNCgljLTEzLjk0OS0xMy45NS0xMy45NDktMzYuNjQ4LDAtNTAuNTk5YzYuNTQyLTYuNTQxLDE1LjE3LTEwLjIyNywyNC4zODQtMTAuNDU3bDczLjg2OS03My44NjlsLTguNTM2LTguNTM2DQoJYy0yLjE2Ny0yLjE2Ny01LjQzNS0yLjc5Ny04LjI1Ny0xLjU5TDYyLjk5NCwzNy45NDZjLTcuNTk5LDIuMjg0LTE0Ljg4OCw1LjU4LTIxLjY2Myw5Ljg1NWMtMS45MjksMS4yMTctMy4xOTgsMy4yNDQtMy40NTIsNS41MQ0KCWMtMC4yLDEuNzk0LDAuMjU0LDMuNTgzLDEuMjUyLDUuMDVMMjQuMTY4LDczLjMyNGMtMS40NjYtMC45OTctMy4yNTctMS40NTEtNS4wNDktMS4yNTFjLTIuMjY3LDAuMjUzLTQuMjk0LDEuNTIzLTUuNTExLDMuNDUxDQoJQzMuMDY0LDkyLjIzMy0xLjU5NywxMTIuMzExLDAuNDg1LDEzMi4wNTljMi4xMTIsMjAuMDUxLDExLjE0MywzOC45NTksMjUuNDI1LDUzLjI0MmMxNi43MTIsMTYuNzExLDM4LjkzMiwyNS45MTUsNjIuNTY4LDI1LjkxNg0KCWMwLjAwMiwwLDAuMDAxLDAsMC4wMDMsMGMxNi43NjksMCwzMy4wOTQtNC43MDgsNDcuMjA3LTEzLjYxM2MxLjkyOS0xLjIxNywzLjE5OC0zLjI0NSwzLjQ1Mi01LjUxMQ0KCWMwLjItMS43OTMtMC4yNTUtMy41ODItMS4yNTItNS4wNDlsMTQuOTYyLTE0Ljk2M2MxLjQ2NywwLjk5OCwzLjI1NCwxLjQ1NSw1LjA1MSwxLjI1MmMyLjI2Ni0wLjI1Myw0LjI5My0xLjUyMyw1LjUxLTMuNDUyDQoJYzMuNjUyLTUuNzg4LDYuNTgzLTExLjk4NSw4Ljc4NC0xOC40MjlsMTMuODU0LDAuNDk3YzAuMDkxLDAuMDAzLDAuMTgzLDAuMDA1LDAuMjczLDAuMDA1YzIuMDkyLDAsMy45OTEtMC44NjgsNS4zNTctMi4yNjYNCgljMC4wNDEtMC4wMzksMC4wODUtMC4wNzMsMC4xMjUtMC4xMTNsMTguMjktMTguMjkxYzIuMjM2LTIuMjM2LDMuNDY5LTUuMjEsMy40NjktOC4zNzNTMjEyLjMzLDExNi43NzUsMjEwLjExNiwxMTQuNTYxeiIvPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPC9zdmc+DQo=
      mediatype: image/svg+xml
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: ServiceConfig
      name: serviceconfigs.cloudnative.redhat.com
      version: v1alpha1
      displayName: Service Config
      description: Represents a Service Configuration
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  install:
    spec:
      deployments:
      - name: service-config-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: service-config-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: service-config-operator
            spec:
              containers:
              - command:
                - service-config-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: service-config-operator
                image: quay.io/cvicensa/service-config-operator:v0.0.1
                imagePullPolicy: Always
                name: service-config-operator
                resources: {}
              serviceAccountName: service-config-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - service-config-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - cloudnative.redhat.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: service-config-operator
    strategy: deployment


